### ISSUE TITLE
Week May 19

### ISSUE THREAD

**Issue by kevxucs** [JangoBoogaloo/LeetCode#10]
Easy
https://leetcode.com/problems/maximum-product-of-three-numbers/
https://leetcode.com/problems/non-decreasing-array/
https://leetcode.com/problems/shortest-unsorted-continuous-subarray/
https://leetcode.com/problems/max-consecutive-ones/
https://leetcode.com/problems/third-maximum-number/
https://leetcode.com/problems/missing-number/
https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/
https://leetcode.com/problems/add-to-array-form-of-integer/
https://leetcode.com/problems/pascals-triangle/
https://leetcode.com/problems/partition-array-into-three-parts-with-equal-sum/

Medium
https://leetcode.com/tag/array/
https://leetcode.com/problems/jump-game/
https://leetcode.com/problems/spiral-matrix/
https://leetcode.com/problems/search-in-rotated-sorted-array/
https://leetcode.com/problems/next-permutation/

**Comment by JangoBoogaloo** [comment]
Easy
https://leetcode.com/problems/min-cost-climbing-stairs/
https://leetcode.com/problems/toeplitz-matrix/
https://leetcode.com/problems/image-smoother/
https://leetcode.com/problems/maximum-average-subarray-i/
https://leetcode.com/problems/shortest-unsorted-continuous-subarray/
https://leetcode.com/problems/find-common-characters/
https://leetcode.com/problems/longest-continuous-increasing-subsequence/
https://leetcode.com/problems/find-pivot-index/
https://leetcode.com/problems/can-place-flowers/
https://leetcode.com/problems/k-diff-pairs-in-an-array/
