### ISSUE TITLE
Questions For June 2

### ISSUE THREAD

**Issue by JangoBoogaloo** [JangoBoogaloo/LeetCode#11]
Jango Array Questions
https://github.com/JangoBoogaloo/LeetCode/wiki/Array-(20190601)

**Comment by kevxucs** [comment]
https://leetcode.com/problems/binary-prefix-divisible-by-5/
https://leetcode.com/problems/find-common-characters/
https://leetcode.com/problems/valid-mountain-array/
https://leetcode.com/problems/monotonic-array/
https://leetcode.com/problems/fair-candy-swap/
